environments:
  {{ $.Environment.Name }}: {{ $envPrefix := printf "%v-" $.Environment.Name }}
---
releases:
  - name: {{ $.Environment.Name }}-{{ .Values.caName }}
    chart: ../hlf-ca
    version: 0.1.0
    namespace: {{ $.Namespace }}

    values:
      - fullnameOverride: {{ .Values.caName }}-hlf-ca
        nodeName: ca
        orgName: orderer

        maintenanceMode: false

        image:
          tag: 1.4.8

        ingress:
          enabled: false

        persistence:
          enabled: {{ eq .Values.useExternalDB "false" }}
          storageClass: ""
          accessMode: ReadWriteOnce
          size: {{ .Values.caPersistenceSize }}

        caName: {{ .Values.caName }}

        {{ if eq .Values.useExternalDB "true" }}
        externalDatabase:
          type: postgres
          host: {{ .Values.ordererCADBHost }}
          port: 5432
          username: root
          password: db_password
          database: fabric_ca
        {{ end }}

        adminUsername: {{ .Values.adminUsername }}
        adminPassword: {{ .Values.adminPassword }}

        config:
          hlfToolsVersion: 1.4.8
          debug: {{ .Values.debug }}
          enableTLSWithoutIngress: true
          useIssuedTLS: true
          useIssuedCACert: true

        csrHosts: {{ .Values.caName }},{{ .Values.caName }}-hlf-ca, {{ .Values.caName }}-hlf-ca.{{ $.Namespace }}.svc.cluster.local,localhost
  
    set:
      - name: namespace
        value: {{ $.Namespace }}

    wait: true